# -*- coding: utf-8 -*-
"""Ai project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6oUEEi6WCvrcVsEuRqCb1gWj5mZwUMW
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, Input
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

#  LOAD DATASET
base_folder = "/content/drive/MyDrive/6th semester/archive"

happy_folder = os.path.join(base_folder, "happy")
sad_folder = os.path.join(base_folder, "Sad")
angry_folder = os.path.join(base_folder, "Angry")

def load_images_from_folder(folder, img_size=(128, 128)):
    images = []
    if not os.path.exists(folder):
        print(f"⚠️ Folder not found: {folder}")
        return images
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder, filename))
        if img is not None:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, img_size)
            images.append(img)
    return images

happy_images = load_images_from_folder(happy_folder)
sad_images = load_images_from_folder(sad_folder)
angry_images = load_images_from_folder(angry_folder)

print(f" Happy: {len(happy_images)}, Sad: {len(sad_images)}, Angry: {len(angry_images)}")

if len(happy_images) == 0 or len(sad_images) == 0 or len(angry_images) == 0:
    raise ValueError(" Images nahi mili! Path check karein.")

happy_labels = [0] * len(happy_images)
sad_labels = [1] * len(sad_images)
angry_labels = [2] * len(angry_images)

X = np.array(happy_images + sad_images + angry_images)
y = np.array(happy_labels + sad_labels + angry_labels)

X = X.astype('float32') / 255.0
y = to_categorical(y, 3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f" Train: {X_train.shape[0]}, Test: {X_test.shape[0]}")

#  DATA AUGMENTATION
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.15,
    height_shift_range=0.15,
    zoom_range=0.15,
    horizontal_flip=True,
    fill_mode='nearest'
)

#  TRANSFER LEARNING (MobileNetV2)
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(128, 128, 3)
)
base_model.trainable = False  # Pre-trained weights freeze

model = Sequential([
    Input(shape=(128, 128, 3)),
    base_model,
    GlobalAveragePooling2D(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
print(model.summary())

#  CALLBACKS
early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-7)

# TRAINING
history = model.fit(
    datagen.flow(X_train, y_train, batch_size=16),
    epochs=50,
    validation_data=(X_test, y_test),
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# EVALUATION
test_loss, test_acc = model.evaluate(X_test, y_test)
train_loss, train_acc = model.evaluate(X_train, y_train)

print(f" Train Accuracy: {train_acc*100:.2f}%")
print(f"Test Accuracy: {test_acc*100:.2f}%")

model.save("facial_expression_model_mobilenet.keras")
print(" Model saved successfully!")

# TRAINING GRAPHS
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.title('Accuracy over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid()
plt.tight_layout()
plt.savefig("training_history_mobilenet.png")
plt.show()

# CONFUSION MATRIX
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Happy', 'Sad', 'Angry'],
            yticklabels=['Happy', 'Sad', 'Angry'])
plt.title('Confusion Matrix - MobileNetV2')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.savefig("confusion_matrix_mobilenet.png")
plt.show()

print("\n Classification Report:")
print(classification_report(y_true, y_pred_classes, target_names=['Happy', 'Sad', 'Angry']))

# EXTRA: SAMPLE PREDICTION
def predict_single_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (128, 128))
    img = img.astype('float32') / 255.0
    img = np.expand_dims(img, axis=0)
    pred = model.predict(img)
    class_names = ['Happy', 'Sad', 'Angry']
    return class_names[np.argmax(pred)]

"""Test image

"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from google.colab import files
import os

#LOAD MODEL
model_path = "/content/facial_expression_model_mobilenet.keras"

if os.path.exists(model_path):
    model = load_model(model_path)
    print(" Model loaded successfully!")
else:
    print("Model not found! Please train the model first.")
    print("   Run the training code above first.")

# CLASSES
emotions = {0: "Happy", 1: "Sad", 2: "Angry "}

# PREDICT FUNCTION
def predict_image(image_path):
    """
    Single image par prediction karega
    """
    # Read image
    img = cv2.imread(image_path)
    if img is None:
        print(f" Image not found: {image_path}")
        return None

    # Convert BGR to RGB
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Resize to 128x128
    img_resized = cv2.resize(img_rgb, (128, 128))

    # Normalize
    img_normalized = img_resized.astype('float32') / 255.0

    # Add batch dimension
    img_input = np.expand_dims(img_normalized, axis=0)

    # Predict
    predictions = model.predict(img_input)
    pred_class = np.argmax(predictions)
    confidence = np.max(predictions) * 100

    return {
        'class': pred_class,
        'emotion': emotions[pred_class],
        'confidence': confidence,
        'predictions': predictions[0],
        'image': img_rgb
    }

# UPLOAD & TEST
print("\n" + "="*50)
print("Please upload an image to test...")
print("="*50 + "\n")

# Upload image from your computer
uploaded = files.upload()

# Process each uploaded image
for filename in uploaded.keys():
    print(f"\n Testing: {filename}")
    print("-" * 40)

    result = predict_image(filename)

    if result is None:
        continue

    # Display image with prediction
    plt.figure(figsize=(8, 6))
    plt.imshow(result['image'])
    plt.title(f"Predicted: {result['emotion']} ({result['confidence']:.1f}%)",
              fontsize=14, color='green' if result['confidence'] > 70 else 'orange')
    plt.axis('off')
    plt.tight_layout()
    plt.show()

    # Print detailed results
    print(f"\n Raw Predictions:")
    for i, (emotion, prob) in enumerate(zip(emotions.values(), result['predictions'])):
        bar = " " * int(prob * 50) + " " * (50 - int(prob * 50))
        print(f"   {emotion}: {prob*100:.2f}% {bar}")

    print(f"\n Final Prediction: {result['emotion']}")
    print(f"   Confidence: {result['confidence']:.2f}%")

    if result['confidence'] > 80:
        print("   High Confidence - Model is very sure!")
    elif result['confidence'] > 60:
        print("   Medium Confidence - Model is somewhat sure.")
    else:
        print("   Low Confidence - Please try a clearer image.")

    print("-" * 40 + "\n")

print("Testing complete!")

from google.colab import files
files.download("facial_expression_model_mobilenet.keras")

from tensorflow.keras.models import load_model
from google.colab import files

# Load .keras model
model = load_model("/content/facial_expression_model_mobilenet.keras")

# Save as .h5 with older format
model.save("facial_expression_model_mobilenet.h5", save_format='h5')

# Download
files.download("facial_expression_model_mobilenet.h5")

from tensorflow.keras.models import load_model, model_from_json

# Load model
model = load_model("/content/facial_expression_model_mobilenet.h5")

# Save architecture as JSON
model_json = model.to_json()
with open("model_architecture.json", "w") as json_file:
    json_file.write(model_json)

# Save weights separately
model.save_weights("model_weights.h5")

# Download both files
from google.colab import files
files.download("model_architecture.json")
files.download("model_weights.h5")